site_name: Akonadi Next
pages:
- Home: index.md
- Terminology: terminology.md
- Overview: design.md
- Resource: resource.md
- Storage: storage.md
- Logging: logging.md
- "Client API": clientapi.md
- akonadish: akonadish.md
- "Application Domain Types": applicationdomaintypes.md
- "Extending Akonadi": extendingakonadi.md
theme: readthedocs
