site_name: Sink
pages:
- Home: index.md
- Terminology: terminology.md
- Overview: design.md
- Resource: resource.md
- Storage: storage.md
- Logging: logging.md
- "Client API": clientapi.md
- sinksh: sinksh.md
- "Application Domain Types": applicationdomaintypes.md
- "Extending Sink": extending.md
- Building: building.md
theme: readthedocs
