site_name: Sink
pages:
- Home: index.md
- Design:
    - Terminology: terminology.md
    - "Design Goals": designgoals.md
    - Overview: design.md
    - "Client API": clientapi.md
    - "Application Domain Types": applicationdomaintypes.md
    - Queries: queries.md
    - Resource: resource.md
    - "Store and Indexes": storage.md
    - Logging: logging.md
    - "Tradeoffs and Design Decisions": tradeoffs.md
- Development:
    - "Extending Sink": extending.md
- Building: building.md
- "Sink Shell": sinksh.md
theme: readthedocs
